# Generated by Django 5.1.2 on 2024-10-15 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dashboards", "0001_initial"),
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservideoprogress",
            name="user_progress",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_progresses",
                to="progress.userprogress",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="expirationnotification",
            unique_together={("enrollment", "notification_date")},
        ),
        migrations.AlterUniqueTogether(
            name="userlearningrecord",
            unique_together={("user", "date", "major_category")},
        ),
    ]
