# Generated by Django 5.1.1 on 2024-09-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="majorcategory",
            name="price",
            field=models.PositiveIntegerField(default=0, verbose_name="강의가격"),
        ),
    ]
