# Generated by Django 5.1.2 on 2024-10-15 01:37

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="수강 완료 여부"),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="마지막 접속 시간",
                    ),
                ),
                (
                    "progress_percent",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="수강 진행률(%)",
                    ),
                ),
                (
                    "time_spent",
                    models.DurationField(
                        default=datetime.timedelta, verbose_name="수강 진행 시간"
                    ),
                ),
                (
                    "last_position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="마지막 시청 위치(초 단위)"
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresses",
                        to="courses.enrollment",
                        verbose_name="수강 등록",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "수강 진행",
                "verbose_name_plural": "수강 진행 목록",
            },
        ),
    ]
