# Generated by Django 5.1.1 on 2024-09-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogress",
            name="last_position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
