# Generated by Django 5.1.2 on 2024-10-15 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("progress", "0001_initial"),
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogress",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progresses",
                to="videos.video",
                verbose_name="강의",
            ),
        ),
    ]
