# Generated by Django 5.1.1 on 2024-09-28 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_majorcategory_price"),
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="minor_category",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="courses.minorcategory",
                verbose_name="소분류",
            ),
            preserve_default=False,
        ),
    ]
