# Generated by Django 5.1.1 on 2024-10-07 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="미션 제목")),
                ("description", models.TextField(verbose_name="미션 설명")),
                (
                    "mission_type",
                    models.CharField(
                        choices=[("MID", "중간 미션"), ("FINAL", "기말 미션")],
                        max_length=5,
                        verbose_name="미션 유형",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="미션 순서")),
                (
                    "passing_score",
                    models.PositiveIntegerField(default=60, verbose_name="합격 점수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "minor_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="courses.minorcategory",
                        verbose_name="소분류",
                    ),
                ),
            ],
            options={
                "verbose_name": "미션",
                "verbose_name_plural": "미션 목록",
                "ordering": ["order"],
                "unique_together": {("minor_category", "order")},
            },
        ),
        migrations.CreateModel(
            name="MissionSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="제출 시간"),
                ),
                ("total_score", models.FloatField(default=0, verbose_name="총점")),
                (
                    "is_passed",
                    models.BooleanField(default=False, verbose_name="통과 여부"),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="missions.mission",
                        verbose_name="미션",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "미션 제출",
                "verbose_name_plural": "미션 제출 목록",
                "unique_together": {("user", "mission")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[("MCQ", "5지선다형"), ("CODE", "코드 제출형")],
                        max_length=4,
                        verbose_name="문제 유형",
                    ),
                ),
                ("content", models.TextField(verbose_name="문제 내용")),
                ("order", models.PositiveIntegerField(verbose_name="문제 순서")),
                ("points", models.PositiveIntegerField(default=1, verbose_name="배점")),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="missions.mission",
                        verbose_name="미션",
                    ),
                ),
            ],
            options={
                "verbose_name": "문제",
                "verbose_name_plural": "문제 목록",
                "ordering": ["order"],
                "unique_together": {("mission", "order")},
            },
        ),
        migrations.CreateModel(
            name="MultipleChoiceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.CharField(max_length=200, verbose_name="선택지 내용"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="정답 여부"),
                ),
                ("order", models.PositiveIntegerField(verbose_name="선택지 순서")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="missions.question",
                        verbose_name="문제",
                    ),
                ),
            ],
            options={
                "verbose_name": "선택지",
                "verbose_name_plural": "선택지 목록",
                "ordering": ["order"],
                "unique_together": {("question", "order")},
            },
        ),
        migrations.CreateModel(
            name="CodeQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initial_code",
                    models.TextField(blank=True, verbose_name="초기 코드"),
                ),
                ("test_cases", models.JSONField(verbose_name="테스트 케이스")),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_question",
                        to="missions.question",
                        verbose_name="문제",
                    ),
                ),
            ],
            options={
                "verbose_name": "코드 제출 문제",
                "verbose_name_plural": "코드 제출 문제 목록",
            },
        ),
        migrations.CreateModel(
            name="MultipleChoiceSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="제출 시간"),
                ),
                (
                    "score",
                    models.FloatField(blank=True, null=True, verbose_name="점수"),
                ),
                (
                    "mission_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiple_choice_submissions",
                        to="missions.missionsubmission",
                        verbose_name="미션 제출",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="missions.multiplechoiceoption",
                        verbose_name="선택한 답변",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="missions.question",
                        verbose_name="문제",
                    ),
                ),
            ],
            options={
                "verbose_name": "객관식 문제 제출",
                "verbose_name_plural": "객관식 문제 제출 목록",
                "unique_together": {("mission_submission", "question")},
            },
        ),
        migrations.CreateModel(
            name="CodeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="제출 시간"),
                ),
                (
                    "score",
                    models.FloatField(blank=True, null=True, verbose_name="점수"),
                ),
                ("submitted_code", models.TextField(verbose_name="제출한 코드")),
                (
                    "mission_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_submissions",
                        to="missions.missionsubmission",
                        verbose_name="미션 제출",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="missions.question",
                        verbose_name="문제",
                    ),
                ),
            ],
            options={
                "verbose_name": "코드 문제 제출",
                "verbose_name_plural": "코드 문제 제출 목록",
                "unique_together": {("mission_submission", "question")},
            },
        ),
    ]
