# Generated by Django 5.1.1 on 2024-10-01 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.PositiveIntegerField()),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("receipt_url", models.URLField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "결제대기"),
                            ("COMPLETED", "결제완료"),
                            ("FAILED", "결제실패"),
                            ("CANCELLED", "결제취소"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "refund_status",
                    models.CharField(
                        choices=[
                            ("NOT_REQUESTED", "요청없음"),
                            ("REQUESTED", "요청됨"),
                            ("COMPLETED", "요청완료"),
                            ("FAILED", "요청실패"),
                        ],
                        default="NOT_REQUESTED",
                        max_length=20,
                    ),
                ),
                (
                    "major_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="courses.majorcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
