# Generated by Django 5.1.1 on 2024-10-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="user",
            new_name="username",
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("ready", "미결제"),
                    ("paid", "결제완료"),
                    ("cancelled", "결제취소"),
                    ("failed", "결제실패"),
                ],
                default="ready",
                max_length=20,
            ),
        ),
    ]
