# Generated by Django 5.1.1 on 2024-10-01 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_rename_user_payment_username_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="username",
            new_name="user",
        ),
    ]
