# Generated by Django 5.1.1 on 2024-09-25 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_payment_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="amount",
            new_name="total_amount",
        ),
    ]
