# Generated by Django 5.1.1 on 2024-09-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_rename_amount_payment_total_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="course",
            new_name="major_category",
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "결제대기"),
                    ("COMPLETED", "결제완료"),
                    ("FAILED", "결제실패"),
                    ("CANCELLED", "결제취소"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("NOT_REQUESTED", "요청없음"),
                    ("REQUESTED", "요청됨"),
                    ("COMPLETED", "요청완료"),
                    ("FAILED", "요청실패"),
                ],
                default="NOT_REQUESTED",
                max_length=20,
            ),
        ),
    ]
