# Generated by Django 5.1.1 on 2024-09-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_rename_course_payment_major_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="merchant_uid",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "결제대기"),
                    ("COMPLETED", "결제완료"),
                    ("FAILED", "결제실패"),
                    ("CANCELLED", "결제취소"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("NOT_REQUESTED", "요청 없음"),
                    ("REQUESTED", "환불 요청됨"),
                    ("COMPLETED", "환불 완료"),
                    ("FAILED", "환불 실패"),
                ],
                default="NOT_REQUESTED",
                max_length=20,
            ),
        ),
    ]
