# Generated by Django 5.1.1 on 2024-09-25 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_date",
                    models.DateTimeField(auto_now_add=True, help_text="수료증 발급일"),
                ),
                (
                    "certificate_id",
                    models.CharField(
                        help_text="수료증 고유 ID", max_length=100, unique=True
                    ),
                ),
                (
                    "major_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="수료한 대분류 코스",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.majorcategory",
                    ),
                ),
                (
                    "minor_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="수료한 소분류 코스",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.minorcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="수료증을 받은 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
