# Generated by Django 5.1.1 on 2024-09-29 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Certificate",
        ),
    ]
