name: Lint Python Code with Ruff

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run Ruff on changed files in src directory
        uses: chartboost/ruff-action@v1
        with:
          changed-files: 'true'
          src: './src'
